### ISSUE TITLE
METAR not available in XP12

### ISSUE THREAD

**Issue by argonius-ch** [fpw/avitab#129]
In XP12 the current METAR is no longer in METAR.rwx and thus AviTab 0.5.1 will not display METAR info.

**Comment by airfightergr** [comment]
If you don't know that already, METARs are now in `X-Plane 12/Output/real weather/` folder, with naming format `METAR-year-month-date-hours.minutes-ZULU.txt`

**Comment by fpw** [comment]
Thanks, I'm aware of that. However, I was informed by LR that it's not a good idea to simply load the latest TXT from there. There are many edge cases where this is wrong, for example when setting up a flight in the past or when pausing the simulator. 
LR will add a new dataref to export the currently used file, the fix has to wait for that.

**Comment by fpw** [comment]
This is now tracked at LR as XPD-13331.

**Comment by argonius-ch** [comment]
While waiting for LR to solve XPD-13331, this can serve as a convenient workaround: https://github.com/biuti/XplaneNoaaWeather/releases/tag/v12.0.0-alpha.5

**Comment by fpw** [comment]
XPD-13331 has now been fixed by Laminar, but the solution is a new plugin API and there is no new plugin SDK with these functions yet. Also, this will mean that AviTab won't be compatible with X-Plane 11 anymore if I start using that API. Will think about doing two versions or focusing on XP12 only.

**Comment by CrazyKnightGR** [comment]
LR has release v4.0.0 SDK that support simply access to METAR

**Comment by jonaseberle** [comment]
It is still not there as far as I see. The SDK 4.0.0 Beta 1 is from last September.
(https://developer.x-plane.com/sdk/plugin-sdk-downloads/)

**Comment by CrazyKnightGR** [comment]
> It is still not there as far as I see. The SDK 4.0.0 Beta 1 is from last September. (https://developer.x-plane.com/sdk/plugin-sdk-downloads/)


Doesn't matter the developer of AviTab would find it (**API** XPLM_64 was updated -library-)

Public Beta – 12.04b1 
.........
XPD-13421 – **Simple SDK Weather API** – METAR Access + lat/lon weather fetch.
.........

XPLMGetMETARForAirport
XPLMGetWeatherAtLocation

**Comment by fpw** [comment]
Implemented this now, it will be part of the next AviTab release that's coming out soon.
